# Generated by Django 5.0.6 on 2024-07-28 06:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_course_attendingcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('street', models.CharField(max_length=255)),
                ('suite', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=10)),
                ('geo_lat', models.CharField(max_length=50)),
                ('geo_lng', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField()),
                ('company_name', models.CharField(max_length=255)),
                ('company_catchPhrase', models.CharField(max_length=255)),
                ('company_bs', models.CharField(max_length=255)),
            ],
        ),
    ]
