# Generated by Django 5.0.6 on 2024-06-14 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountuser',
            new_name='mysite_acco_account_317046_idx',
            old_name='mysite_acco_account_7dc129_idx',
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
