# Generated by Django 5.0.6 on 2024-06-19 01:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_accountuser_account_user_id_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountuser',
            new_name='mysite_acco_account_7dc129_idx',
            old_name='mysite_acco_account_317046_idx',
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_related_user',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
